name: "Stream mqtt from Enphase Envoy"
description: "Converts Envoy Json to mqtt - V5, v7 and v8 with batteries"
version: "1.0.20"
slug: "envoy_to_mqtt_json"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
options:
  MQTT_HOST: ip.address.of.homeasistant
  MQTT_USER: mqtt.user
  MQTT_PASSWORD: mqtt.password
  MQTT_PORT: 1883
  MQTT_TOPIC: /envoy/json
  ENVOY_HOST: envoy.local
  ENVOY_USE_HTTPS: false
  ENVOY_PASSWORD: enter.envoy.password
  ENVOY_USER: enter.enphase.userid@email.com
  ENVOY_USER_PASS: enter.enphase.password
  USE_FREEDS: False
  BATTERY_INSTALLED: False
  DEBUG: False

schema:
  MQTT_HOST: str
  MQTT_USER: str
  MQTT_PASSWORD: password
  MQTT_PORT: int
  MQTT_TOPIC: str
  ENVOY_HOST: str
  ENVOY_USE_HTTPS: bool
  ENVOY_PASSWORD: password
  ENVOY_USER: str
  ENVOY_USER_PASS: password
  USE_FREEDS: bool
  BATTERY_INSTALLED: bool
  DEBUG: bool
