name: "Stream mqtt from Enphase Envoy"
description: "Converts Envoy Json to mqtt"
version: "1.0.9"
slug: "envoy_to_mqtt_json"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
options:

  MQTT_HOST: ip.address.of.homeasistant
  MQTT_USER: mqtt.user
  MQTT_PASSWORD: mqtt.password
  MQTT_PORT: 1883
  envoy_host: envoy.local
  envoy_password: secret
  TOPIC_FREEDS: Inverter/GridWatts

schema:
  MQTT_HOST: str
  MQTT_USER: str
  MQTT_PASSWORD: str
  MQTT_PORT: int
  envoy_host: str
  envoy_password: str  
  TOPIC_FREEDS: str
