name: "Stream mqtt from Enphase Envoy"
description: "Converts Envoy Json to mqtt firmware v5 or v7"
version: "1.0.11"
slug: "envoy_to_mqtt_json"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
options:
  MQTT_HOST: ip.address.of.homeasistant
  MQTT_USER: mqtt.user
  MQTT_PASSWORD: mqtt.password
  MQTT_PORT: 1883
  MQTT_TOPIC: /envoy/json
  ENVOY_HOST: envoy.local
  ENVOY_USER: enter.enphase.userid@email.com
  ENVOY_USER_PASS: enter.enphase.password
  USE_FREEDS: False

schema:
  MQTT_HOST: str
  MQTT_USER: str
  MQTT_PASSWORD: password
  MQTT_PORT: int
  MQTT_TOPIC: str
  ENVOY_HOST: str
  ENVOY_USER: str
  ENVOY_USER_PASS: str
  USE_FREEDS: bool